platform:ios,10.0
use_frameworks!
target:testRXLogin do

pod 'Moya', '8.0.2'
pod 'Moya/RxSwift'
pod 'Alamofire', '4.4.0'
pod 'RxSwift', '3.0.0'
pod 'RxCocoa', '3.0.0'
pod 'RxDataSources', '1.0.3'
pod 'ObjectMapper', '2.2.0'
pod 'SwiftyJSON', '3.1.4'
pod 'MBProgressHUD', '1.0.0'
pod 'MJRefresh', '3.1.12'

end
